# Generated by Django 4.2.3 on 2023-07-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listings_comments_bids_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion & Accessories', 'Fashion & Accessories'), ('Home & Garden', 'Home & Garden'), ('Books & Media', 'Books & Media'), ('Health & Beauty', 'Health & Beauty'), ('Toys & Games', 'Toys & Games'), ('Arts & Crafts', 'Arts & Crafts'), ('Sports & Outdoor', 'Sports & Outdoor'), ('Vehicles & Parts', 'Vehicles & Parts'), ('Jewelry & Watches', 'Jewelry & Watches'), ('Computers & Software', 'Computers & Software'), ('Collectibles & Art', 'Collectibles & Art'), ('Musical Instruments', 'Musical Instruments'), ('Business & Industrial', 'Business & Industrial'), ('Baby & Kids', 'Baby & Kids'), ('Pets Supplies', 'Pets Supplies'), ('Travel & Experiences', 'Travel & Experiences'), ('Real Estate', 'Real Estate'), ('Tickets & Events', 'Tickets & Events'), ('Other', 'Other')], default='Electronics', max_length=64),
        ),
    ]
