# Generated by Django 4.2.3 on 2023-07-30 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listings_current_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winning_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
